# Generated by Django 5.1.2 on 2024-11-01 15:36

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('user_auth_app', '0003_rename_uid_userprofile_user'),
    ]

    operations = [
        migrations.DeleteModel(
            name='UserProfile',
        ),
    ]
