# Generated by Django 5.1.2 on 2024-10-23 10:44

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Contact',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('color', models.IntegerField()),
                ('email', models.EmailField(max_length=254)),
                ('name', models.CharField(max_length=255)),
                ('password', models.CharField(max_length=255)),
                ('phone', models.CharField(max_length=20)),
                ('user', models.BooleanField()),
            ],
        ),
        migrations.CreateModel(
            name='Task',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('categoryTask', models.CharField(max_length=255)),
                ('descriptionTask', models.TextField()),
                ('priorityTask', models.CharField(max_length=50)),
                ('status', models.IntegerField()),
                ('timeDeadlineTask', models.DateTimeField()),
                ('titleTask', models.CharField(max_length=255)),
                ('nameAssignedTask', models.ManyToManyField(related_name='tasks', to='join_api.contact')),
            ],
        ),
        migrations.CreateModel(
            name='SubTask',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('subTaskName', models.CharField(max_length=255)),
                ('statusSubTask', models.BooleanField(default=False)),
                ('task', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='subtasks', to='join_api.task')),
            ],
        ),
    ]
