# Generated by Django 5.1.2 on 2024-10-24 09:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('join_api', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='contact',
            name='password',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='task',
            name='categoryTask',
            field=models.CharField(choices=[('Technical task', 'Technical task'), ('User story', 'User story')], default='Technical task', max_length=255),
        ),
        migrations.AlterField(
            model_name='task',
            name='priorityTask',
            field=models.CharField(choices=[('Low', 'Low Priority'), ('Medium', 'Medium Priority'), ('High', 'High Priority')], default='Medium', max_length=50),
        ),
        migrations.AlterField(
            model_name='task',
            name='status',
            field=models.IntegerField(choices=[(1, 'To Do'), (2, 'In Progress'), (3, 'Await Feedback'), (4, 'Done')], default=1),
        ),
    ]
