# Generated by Django 5.1.2 on 2024-10-24 12:26

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('join_api', '0003_alter_subtask_task_alter_task_nameassignedtask'),
    ]

    operations = [
        migrations.AlterField(
            model_name='subtask',
            name='task',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='subtasks', to='join_api.task'),
        ),
        migrations.AlterField(
            model_name='task',
            name='nameAssignedTask',
            field=models.ManyToManyField(related_name='tasks', to='join_api.contact'),
        ),
    ]
