# Generated by Django 5.1.2 on 2024-10-24 12:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('join_api', '0004_alter_subtask_task_alter_task_nameassignedtask'),
    ]

    operations = [
        migrations.AlterField(
            model_name='task',
            name='timeDeadlineTask',
            field=models.DateField(),
        ),
    ]
