# Generated by Django 5.1.2 on 2024-10-28 11:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('join_api', '0005_alter_task_timedeadlinetask'),
    ]

    operations = [
        migrations.AlterField(
            model_name='task',
            name='descriptionTask',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='task',
            name='priorityTask',
            field=models.CharField(choices=[('low', 'Low Priority'), ('medium', 'Medium Priority'), ('urgent', 'High Priority')], default='medium', max_length=50),
        ),
    ]
