# Generated by Django 5.1.2 on 2024-10-29 06:40

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('join_api', '0006_alter_task_descriptiontask_alter_task_prioritytask'),
    ]

    operations = [
        migrations.AlterField(
            model_name='subtask',
            name='task',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='subTasks', to='join_api.task'),
        ),
    ]
