# Generated by Django 5.1.2 on 2024-10-29 17:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('join_api', '0007_alter_subtask_task'),
    ]

    operations = [
        migrations.AlterField(
            model_name='contact',
            name='phone',
            field=models.CharField(blank=True, max_length=20, null=True),
        ),
    ]
