# Generated by Django 5.1.2 on 2024-11-01 15:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('join_api', '0010_remove_contact_uid_alter_contact_user'),
    ]

    operations = [
        migrations.AddField(
            model_name='contact',
            name='isUser',
            field=models.BooleanField(default=False),
        ),
    ]
