# Generated by Django 5.1.2 on 2024-11-01 19:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('join_api', '0012_rename_isuser_contact_is_user_alter_contact_user'),
    ]

    operations = [
        migrations.AlterField(
            model_name='contact',
            name='color',
            field=models.IntegerField(default=0),
        ),
    ]
